stages:
  - testbuild
  - build

before_script:
  - export APP_REVISION="${CI_COMMIT_TAG:-${CI_COMMIT_REF_NAME##*/}-r$CI_PIPELINE_ID}"
  - "export DOCKER_CONFIG_JSON=$(jq 'reduce .[].auth.auths as $item ({}; . + $item) | {auths: .}' <<< $REGISTRIES)"

testbuild:
  stage: testbuild
  script:
    - |
      set -x
      yarn config set registry https://registry.npm.taobao.org --global
      yarn install
      yarn build
  only:
    - merge_requests
  except:
    - schedules

build: 
  stage: build
  script:
    - IMAGES="$(jq -r '. | map(.server + "/" + .pathPrefix + "/" + env.CI_PROJECT_NAME + ":" + env.APP_REVISION) | join(" ")' <<< $REGISTRIES)"
    - docker build --network=host --build-arg CROWDIN_PERSONAL_TOKEN=$CROWDIN_PERSONAL_TOKEN . -t $IMAGES || exit 1
    - while read IMAGE; do
        echo "pushed to $IMAGE";
        docker push $IMAGE || exit 1;
      done < <(jq -r '.[] | .server + "/" + .pathPrefix + "/" + env.CI_PROJECT_NAME + ":" + env.APP_REVISION'<<<$REGISTRIES)
  only:
    - tags
  except:
    - schedules
